# Generated by Django 6.1.1 on 2026-09-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
