# Generated by Django 6.1 on 2026-09-12 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('application_type', models.CharField(default='web_application', max_length=100)),
                ('stack', models.JSONField(default=dict)),
                ('features', models.JSONField(default=list)),
                ('entities', models.JSONField(default=list)),
                ('pages', models.JSONField(default=list)),
                ('user_roles', models.JSONField(default=list)),
                ('assumptions', models.JSONField(default=list)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application_specification', to='projects.project')),
            ],
        ),
    ]
